AllCops:
  Exclude:
    - metadata.rb
    - Rakefile
    - vendor/**/*
    - spec/**/*
    - Gemfile

ConditionalAssignment:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
